version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - tms-network
  backend:
    image: task-management-system:0.0.1
    ports:
      - '8080:8080'
    environment:
      DB_NAME: ${DB_NAME}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: database
    depends_on:
      - database
    networks:
      - tms-network
networks:
  tms-network:
    driver: bridge